<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $array = [
            ['id' => 1, 'state_id' => 1, 'name' => 'آذرشهر'],
            ['id' => 2, 'state_id' => 1, 'name' => 'اسکو'],
            ['id' => 3, 'state_id' => 1, 'name' => 'اهر'],
            ['id' => 4, 'state_id' => 1, 'name' => 'بستان آباد'],
            ['id' => 5, 'state_id' => 1, 'name' => 'بناب'],
            ['id' => 6, 'state_id' => 1, 'name' => 'تبریز'],
            ['id' => 7, 'state_id' => 1, 'name' => 'جلفا'],
            ['id' => 8, 'state_id' => 1, 'name' => 'چار اویماق'],
            ['id' => 9, 'state_id' => 1, 'name' => 'سراب'],
            ['id' => 10, 'state_id' => 1, 'name' => 'شبستر'],
            ['id' => 11, 'state_id' => 1, 'name' => 'عجبشیر'],
            ['id' => 12, 'state_id' => 1, 'name' => 'کلیبر'],
            ['id' => 13, 'state_id' => 1, 'name' => 'مراغه'],
            ['id' => 14, 'state_id' => 1, 'name' => 'مرند'],
            ['id' => 15, 'state_id' => 1, 'name' => 'ملکان'],
            ['id' => 16, 'state_id' => 1, 'name' => 'میانه'],
            ['id' => 17, 'state_id' => 1, 'name' => 'ورزقان'],
            ['id' => 18, 'state_id' => 1, 'name' => 'هریس'],
            ['id' => 19, 'state_id' => 1, 'name' => 'هشترود'],
            ['id' => 20, 'state_id' => 2, 'name' => 'ارومیه'],
            ['id' => 21, 'state_id' => 2, 'name' => 'اشنویه'],
            ['id' => 22, 'state_id' => 2, 'name' => 'بوکان'],
            ['id' => 23, 'state_id' => 2, 'name' => 'پیر انشهر'],
            ['id' => 24, 'state_id' => 2, 'name' => 'تکاب'],
            ['id' => 25, 'state_id' => 2, 'name' => 'چالدران'],
            ['id' => 26, 'state_id' => 2, 'name' => 'خوی'],
            ['id' => 27, 'state_id' => 2, 'name' => 'سردشت'],
            ['id' => 28, 'state_id' => 2, 'name' => 'سلماس'],
            ['id' => 29, 'state_id' => 2, 'name' => 'شاهین دژ'],
            ['id' => 30, 'state_id' => 2, 'name' => 'ماکو'],
            ['id' => 31, 'state_id' => 2, 'name' => 'مهاباد'],
            ['id' => 32, 'state_id' => 2, 'name' => 'میاندوآب'],
            ['id' => 33, 'state_id' => 2, 'name' => 'نقده'],
            ['id' => 34, 'state_id' => 3, 'name' => 'اردبیل'],
            ['id' => 35, 'state_id' => 3, 'name' => 'بیله سوار'],
            ['id' => 36, 'state_id' => 3, 'name' => 'پارس آباد'],
            ['id' => 37, 'state_id' => 3, 'name' => 'خلخال'],
            ['id' => 38, 'state_id' => 3, 'name' => 'کوثر'],
            ['id' => 39, 'state_id' => 3, 'name' => 'گرمی'],
            ['id' => 40, 'state_id' => 3, 'name' => 'مشگین'],
            ['id' => 41, 'state_id' => 3, 'name' => 'نمین'],
            ['id' => 42, 'state_id' => 3, 'name' => 'نیر'],
            ['id' => 43, 'state_id' => 4, 'name' => 'آران و بیدگل'],
            ['id' => 44, 'state_id' => 4, 'name' => 'اردستان'],
            ['id' => 45, 'state_id' => 4, 'name' => 'اصفهان'],
            ['id' => 46, 'state_id' => 4, 'name' => 'برخوار و میمه'],
            ['id' => 47, 'state_id' => 4, 'name' => 'تیران و کرون'],
            ['id' => 48, 'state_id' => 4, 'name' => 'چادگان'],
            ['id' => 49, 'state_id' => 4, 'name' => 'خمینی شهر'],
            ['id' => 50, 'state_id' => 4, 'name' => 'خوانسار'],
            ['id' => 51, 'state_id' => 4, 'name' => 'سمیرم'],
            ['id' => 52, 'state_id' => 4, 'name' => 'شاهین شهر و میمه'],
            ['id' => 53, 'state_id' => 4, 'name' => 'شهر رضا'],
            ['id' => 54, 'state_id' => 4, 'name' => 'سمیرم سفلی'],
            ['id' => 55, 'state_id' => 4, 'name' => 'فریدن'],
            ['id' => 56, 'state_id' => 4, 'name' => 'فریدون شهر'],
            ['id' => 57, 'state_id' => 4, 'name' => 'فلاورجان'],
            ['id' => 58, 'state_id' => 4, 'name' => 'کاشان'],
            ['id' => 59, 'state_id' => 4, 'name' => 'گلپایگان'],
            ['id' => 60, 'state_id' => 4, 'name' => 'لنجان'],
            ['id' => 61, 'state_id' => 4, 'name' => 'مبارکه'],
            ['id' => 62, 'state_id' => 4, 'name' => 'نائین'],
            ['id' => 63, 'state_id' => 4, 'name' => 'نجف آباد'],
            ['id' => 64, 'state_id' => 4, 'name' => 'نطنز'],
            ['id' => 65, 'state_id' => 5, 'name' => 'ساوجبلاق'],
            ['id' => 66, 'state_id' => 5, 'name' => 'کرج'],
            ['id' => 67, 'state_id' => 5, 'name' => 'نظرآباد'],
            ['id' => 68, 'state_id' => 5, 'name' => 'طالقان'],
            ['id' => 69, 'state_id' => 6, 'name' => 'آبدانان'],
            ['id' => 70, 'state_id' => 6, 'name' => 'ایلام'],
            ['id' => 71, 'state_id' => 6, 'name' => 'ایوان'],
            ['id' => 72, 'state_id' => 6, 'name' => 'دره شهر'],
            ['id' => 73, 'state_id' => 6, 'name' => 'دهلران'],
            ['id' => 74, 'state_id' => 6, 'name' => 'شیران و چرداول'],
            ['id' => 75, 'state_id' => 6, 'name' => 'مهران'],
            ['id' => 76, 'state_id' => 7, 'name' => 'بوشهر'],
            ['id' => 77, 'state_id' => 7, 'name' => 'تنگستان'],
            ['id' => 78, 'state_id' => 7, 'name' => 'جم'],
            ['id' => 79, 'state_id' => 7, 'name' => 'دشتستان'],
            ['id' => 80, 'state_id' => 7, 'name' => 'دشتی'],
            ['id' => 81, 'state_id' => 7, 'name' => 'دیر'],
            ['id' => 82, 'state_id' => 7, 'name' => 'دیلم'],
            ['id' => 83, 'state_id' => 7, 'name' => 'کنگان'],
            ['id' => 84, 'state_id' => 7, 'name' => 'گناوه'],
            ['id' => 85, 'state_id' => 8, 'name' => 'اسلام شهر'],
            ['id' => 86, 'state_id' => 8, 'name' => 'پاکدشت'],
            ['id' => 87, 'state_id' => 8, 'name' => 'تهران'],
            ['id' => 88, 'state_id' => 8, 'name' => 'دماوند'],
            ['id' => 89, 'state_id' => 8, 'name' => 'رباط کریم'],
            ['id' => 90, 'state_id' => 8, 'name' => 'ری'],
            ['id' => 91, 'state_id' => 8, 'name' => 'شمیرانات'],
            ['id' => 92, 'state_id' => 8, 'name' => 'شهریار'],
            ['id' => 93, 'state_id' => 8, 'name' => 'فیروزکوه'],
            ['id' => 94, 'state_id' => 8, 'name' => 'ورامین'],
            ['id' => 95, 'state_id' => 9, 'name' => 'اردل'],
            ['id' => 96, 'state_id' => 9, 'name' => 'بروجن'],
            ['id' => 97, 'state_id' => 9, 'name' => 'شهرکرد'],
            ['id' => 98, 'state_id' => 9, 'name' => 'فارسان'],
            ['id' => 99, 'state_id' => 9, 'name' => 'کوهرنگ'],
            ['id' => 100, 'state_id' => 9, 'name' => 'لردگان'],
            ['id' => 101, 'state_id' => 10, 'name' => 'بیرجند'],
            ['id' => 102, 'state_id' => 10, 'name' => 'درمیان'],
            ['id' => 103, 'state_id' => 10, 'name' => 'سرایان'],
            ['id' => 104, 'state_id' => 10, 'name' => 'سر بیشه'],
            ['id' => 105, 'state_id' => 10, 'name' => 'فردوس'],
            ['id' => 106, 'state_id' => 10, 'name' => 'قائن'],
            ['id' => 107, 'state_id' => 10, 'name' => 'نهبندان'],
            ['id' => 108, 'state_id' => 11, 'name' => 'برد سکن'],
            ['id' => 109, 'state_id' => 11, 'name' => 'بجستان'],
            ['id' => 110, 'state_id' => 11, 'name' => 'تایباد'],
            ['id' => 111, 'state_id' => 11, 'name' => 'تحت جلگه'],
            ['id' => 112, 'state_id' => 11, 'name' => 'تربت جام'],
            ['id' => 113, 'state_id' => 11, 'name' => 'تربت حیدریه'],
            ['id' => 114, 'state_id' => 11, 'name' => 'چناران'],
            ['id' => 115, 'state_id' => 11, 'name' => 'جغتای'],
            ['id' => 116, 'state_id' => 11, 'name' => 'جوین'],
            ['id' => 117, 'state_id' => 11, 'name' => 'خلیل آباد'],
            ['id' => 118, 'state_id' => 11, 'name' => 'خواف'],
            ['id' => 119, 'state_id' => 11, 'name' => 'درگز'],
            ['id' => 120, 'state_id' => 11, 'name' => 'رشتخوار'],
            ['id' => 121, 'state_id' => 11, 'name' => 'زاوه'],
            ['id' => 122, 'state_id' => 11, 'name' => 'سبزوار'],
            ['id' => 123, 'state_id' => 11, 'name' => 'سرخس'],
            ['id' => 124, 'state_id' => 11, 'name' => 'فریمان'],
            ['id' => 125, 'state_id' => 11, 'name' => 'قوچان'],
            ['id' => 126, 'state_id' => 11, 'name' => 'طرقبه و شاندیز'],
            ['id' => 127, 'state_id' => 11, 'name' => 'کاشمر'],
            ['id' => 128, 'state_id' => 11, 'name' => 'کلات'],
            ['id' => 129, 'state_id' => 11, 'name' => 'گناباد'],
            ['id' => 130, 'state_id' => 11, 'name' => 'مشهد'],
            ['id' => 131, 'state_id' => 11, 'name' => 'مه ولات'],
            ['id' => 132, 'state_id' => 11, 'name' => 'نیشابور'],
            ['id' => 133, 'state_id' => 12, 'name' => 'اسفراین'],
            ['id' => 134, 'state_id' => 12, 'name' => 'بجنورد'],
            ['id' => 135, 'state_id' => 12, 'name' => 'جاجرم'],
            ['id' => 136, 'state_id' => 12, 'name' => 'شیروان'],
            ['id' => 137, 'state_id' => 12, 'name' => 'فاروج'],
            ['id' => 138, 'state_id' => 12, 'name' => 'مانه و سملقان'],
            ['id' => 139, 'state_id' => 13, 'name' => 'آبادان'],
            ['id' => 140, 'state_id' => 13, 'name' => 'امیدیه'],
            ['id' => 141, 'state_id' => 13, 'name' => 'اندیمشک'],
            ['id' => 142, 'state_id' => 13, 'name' => 'اهواز'],
            ['id' => 143, 'state_id' => 13, 'name' => 'ایذه'],
            ['id' => 144, 'state_id' => 13, 'name' => 'باغ ملک'],
            ['id' => 145, 'state_id' => 13, 'name' => 'بندرماهشهر'],
            ['id' => 146, 'state_id' => 13, 'name' => 'بهبهان'],
            ['id' => 147, 'state_id' => 13, 'name' => 'خرمشهر'],
            ['id' => 148, 'state_id' => 13, 'name' => 'دزفول'],
            ['id' => 149, 'state_id' => 13, 'name' => 'دشت آزادگان'],
            ['id' => 150, 'state_id' => 13, 'name' => 'رامشیر'],
            ['id' => 151, 'state_id' => 13, 'name' => 'رامهرمز'],
            ['id' => 152, 'state_id' => 13, 'name' => 'شادگان'],
            ['id' => 153, 'state_id' => 13, 'name' => 'شوش'],
            ['id' => 154, 'state_id' => 13, 'name' => 'شوشتر'],
            ['id' => 155, 'state_id' => 13, 'name' => 'گتوند'],
            ['id' => 156, 'state_id' => 13, 'name' => 'لالی'],
            ['id' => 157, 'state_id' => 13, 'name' => 'مسجد سلیمان'],
            ['id' => 158, 'state_id' => 13, 'name' => 'هندیجان'],
            ['id' => 159, 'state_id' => 14, 'name' => 'ابهر'],
            ['id' => 160, 'state_id' => 14, 'name' => 'ایجرود'],
            ['id' => 161, 'state_id' => 14, 'name' => 'خدابنده'],
            ['id' => 162, 'state_id' => 14, 'name' => 'خرمدره'],
            ['id' => 163, 'state_id' => 14, 'name' => 'زنجان'],
            ['id' => 164, 'state_id' => 14, 'name' => 'طارم'],
            ['id' => 165, 'state_id' => 14, 'name' => 'ماه نشان'],
            ['id' => 166, 'state_id' => 15, 'name' => 'دامغان'],
            ['id' => 167, 'state_id' => 15, 'name' => 'سمنان'],
            ['id' => 168, 'state_id' => 15, 'name' => 'شاهرود'],
            ['id' => 169, 'state_id' => 15, 'name' => 'گرمسار'],
            ['id' => 170, 'state_id' => 15, 'name' => 'مهدی شهر'],
            ['id' => 171, 'state_id' => 16, 'name' => 'ایرانشهر'],
            ['id' => 172, 'state_id' => 16, 'name' => 'چابهار'],
            ['id' => 173, 'state_id' => 16, 'name' => 'خاش'],
            ['id' => 174, 'state_id' => 16, 'name' => 'دلگان'],
            ['id' => 175, 'state_id' => 16, 'name' => 'زابل'],
            ['id' => 176, 'state_id' => 16, 'name' => 'زاهدان'],
            ['id' => 177, 'state_id' => 16, 'name' => 'زهک'],
            ['id' => 178, 'state_id' => 16, 'name' => 'سراوان'],
            ['id' => 179, 'state_id' => 16, 'name' => 'سرباز'],
            ['id' => 180, 'state_id' => 16, 'name' => 'کنارک'],
            ['id' => 181, 'state_id' => 16, 'name' => 'نیکشهر'],
            ['id' => 182, 'state_id' => 17, 'name' => 'آباده'],
            ['id' => 183, 'state_id' => 17, 'name' => 'ارسنجان'],
            ['id' => 184, 'state_id' => 17, 'name' => 'استهبان'],
            ['id' => 185, 'state_id' => 17, 'name' => 'اقلید'],
            ['id' => 186, 'state_id' => 17, 'name' => 'بوانات'],
            ['id' => 187, 'state_id' => 17, 'name' => 'پاسارگاد'],
            ['id' => 188, 'state_id' => 17, 'name' => 'جهرم'],
            ['id' => 189, 'state_id' => 17, 'name' => 'خرم بید'],
            ['id' => 190, 'state_id' => 17, 'name' => 'خنج'],
            ['id' => 191, 'state_id' => 17, 'name' => 'داراب'],
            ['id' => 192, 'state_id' => 17, 'name' => 'زرین دشت'],
            ['id' => 193, 'state_id' => 17, 'name' => 'سپیدان'],
            ['id' => 194, 'state_id' => 17, 'name' => 'شیراز'],
            ['id' => 195, 'state_id' => 17, 'name' => 'فراشبند'],
            ['id' => 196, 'state_id' => 17, 'name' => 'فسا'],
            ['id' => 197, 'state_id' => 17, 'name' => 'فیروزآباد'],
            ['id' => 198, 'state_id' => 17, 'name' => 'قیر و کارزین'],
            ['id' => 199, 'state_id' => 17, 'name' => 'کازرون'],
            ['id' => 200, 'state_id' => 17, 'name' => 'لارستان'],
            ['id' => 201, 'state_id' => 17, 'name' => 'لامرد'],
            ['id' => 202, 'state_id' => 17, 'name' => 'مرودشت'],
            ['id' => 203, 'state_id' => 17, 'name' => 'ممسنی'],
            ['id' => 204, 'state_id' => 17, 'name' => 'مهر'],
            ['id' => 205, 'state_id' => 17, 'name' => 'نی ریز'],
            ['id' => 206, 'state_id' => 18, 'name' => 'آبیک'],
            ['id' => 207, 'state_id' => 18, 'name' => 'البرز'],
            ['id' => 208, 'state_id' => 18, 'name' => 'بوئین زهرا'],
            ['id' => 209, 'state_id' => 18, 'name' => 'تاکستان'],
            ['id' => 210, 'state_id' => 18, 'name' => 'قزوین'],
            ['id' => 211, 'state_id' => 19, 'name' => 'قم'],
            ['id' => 212, 'state_id' => 20, 'name' => 'بانه'],
            ['id' => 213, 'state_id' => 20, 'name' => 'بیجار'],
            ['id' => 214, 'state_id' => 20, 'name' => 'دیواندره'],
            ['id' => 215, 'state_id' => 20, 'name' => 'سروآباد'],
            ['id' => 216, 'state_id' => 20, 'name' => 'سقز'],
            ['id' => 217, 'state_id' => 20, 'name' => 'سنندج'],
            ['id' => 218, 'state_id' => 20, 'name' => 'قروه'],
            ['id' => 219, 'state_id' => 20, 'name' => 'کامیاران'],
            ['id' => 220, 'state_id' => 20, 'name' => 'مریوان'],
            ['id' => 221, 'state_id' => 21, 'name' => 'بافت'],
            ['id' => 222, 'state_id' => 21, 'name' => 'بردسیر'],
            ['id' => 223, 'state_id' => 21, 'name' => 'بم'],
            ['id' => 224, 'state_id' => 21, 'name' => 'جیرفت'],
            ['id' => 225, 'state_id' => 21, 'name' => 'راور'],
            ['id' => 226, 'state_id' => 21, 'name' => 'رفسنجان'],
            ['id' => 227, 'state_id' => 21, 'name' => 'رودبار جنوب'],
            ['id' => 228, 'state_id' => 21, 'name' => 'زرند'],
            ['id' => 229, 'state_id' => 21, 'name' => 'سیرجان'],
            ['id' => 230, 'state_id' => 21, 'name' => 'شهر بابک'],
            ['id' => 231, 'state_id' => 21, 'name' => 'عنبرآباد'],
            ['id' => 232, 'state_id' => 21, 'name' => 'قلعه گنج'],
            ['id' => 233, 'state_id' => 21, 'name' => 'کرمان'],
            ['id' => 234, 'state_id' => 21, 'name' => 'کوهبنان'],
            ['id' => 235, 'state_id' => 21, 'name' => 'کهنوج'],
            ['id' => 236, 'state_id' => 21, 'name' => 'منوجان'],
            ['id' => 237, 'state_id' => 22, 'name' => 'اسلام آباد غرب'],
            ['id' => 238, 'state_id' => 22, 'name' => 'پاوه'],
            ['id' => 239, 'state_id' => 22, 'name' => 'ثلاث باباجانی'],
            ['id' => 240, 'state_id' => 22, 'name' => 'جوانرود'],
            ['id' => 241, 'state_id' => 22, 'name' => 'دالاهو'],
            ['id' => 242, 'state_id' => 22, 'name' => 'روانسر'],
            ['id' => 243, 'state_id' => 22, 'name' => 'سر پل ذهاب'],
            ['id' => 244, 'state_id' => 22, 'name' => 'سنقر'],
            ['id' => 245, 'state_id' => 22, 'name' => 'صحنه'],
            ['id' => 246, 'state_id' => 22, 'name' => 'قصر شیرین'],
            ['id' => 247, 'state_id' => 22, 'name' => 'کرمانشاه'],
            ['id' => 248, 'state_id' => 22, 'name' => 'کنگاور'],
            ['id' => 249, 'state_id' => 22, 'name' => 'گیلان غرب'],
            ['id' => 250, 'state_id' => 22, 'name' => 'هرسین'],
            ['id' => 251, 'state_id' => 23, 'name' => 'بویر احمد'],
            ['id' => 252, 'state_id' => 23, 'name' => 'بهمئی'],
            ['id' => 253, 'state_id' => 23, 'name' => 'دنا'],
            ['id' => 254, 'state_id' => 23, 'name' => 'کهگیلویه'],
            ['id' => 255, 'state_id' => 23, 'name' => 'گچساران'],
            ['id' => 256, 'state_id' => 24, 'name' => 'آزادشهر'],
            ['id' => 257, 'state_id' => 24, 'name' => 'آق قلا'],
            ['id' => 258, 'state_id' => 24, 'name' => 'بندر گز'],
            ['id' => 259, 'state_id' => 24, 'name' => 'بندر ترکمن'],
            ['id' => 260, 'state_id' => 24, 'name' => 'رامیان'],
            ['id' => 261, 'state_id' => 24, 'name' => 'علی آباد'],
            ['id' => 262, 'state_id' => 24, 'name' => 'کرد کوی'],
            ['id' => 263, 'state_id' => 24, 'name' => 'کلاله'],
            ['id' => 264, 'state_id' => 24, 'name' => 'گرگان'],
            ['id' => 265, 'state_id' => 24, 'name' => 'گنبد کاووس'],
            ['id' => 266, 'state_id' => 24, 'name' => 'مینو دشت'],
            ['id' => 267, 'state_id' => 25, 'name' => 'آستارا'],
            ['id' => 268, 'state_id' => 25, 'name' => 'آستانه اشرفیه'],
            ['id' => 269, 'state_id' => 25, 'name' => 'املش'],
            ['id' => 270, 'state_id' => 25, 'name' => 'بندر انزلی'],
            ['id' => 271, 'state_id' => 25, 'name' => 'رشت'],
            ['id' => 272, 'state_id' => 25, 'name' => 'رضوانشهر'],
            ['id' => 273, 'state_id' => 25, 'name' => 'رودبار'],
            ['id' => 274, 'state_id' => 25, 'name' => 'رودسر'],
            ['id' => 275, 'state_id' => 25, 'name' => 'سیاهکل'],
            ['id' => 276, 'state_id' => 25, 'name' => 'شفت'],
            ['id' => 277, 'state_id' => 25, 'name' => 'صومعه سرا'],
            ['id' => 278, 'state_id' => 25, 'name' => 'طوالش'],
            ['id' => 279, 'state_id' => 25, 'name' => 'فومن'],
            ['id' => 280, 'state_id' => 25, 'name' => 'لاهیجان'],
            ['id' => 281, 'state_id' => 25, 'name' => 'لنگرود'],
            ['id' => 282, 'state_id' => 25, 'name' => 'ماسال'],
            ['id' => 283, 'state_id' => 26, 'name' => 'ازنا'],
            ['id' => 284, 'state_id' => 26, 'name' => 'الیگودرز'],
            ['id' => 285, 'state_id' => 26, 'name' => 'بروجرد'],
            ['id' => 286, 'state_id' => 26, 'name' => 'پلدختر'],
            ['id' => 287, 'state_id' => 26, 'name' => 'خرم آباد'],
            ['id' => 288, 'state_id' => 26, 'name' => 'دورود'],
            ['id' => 289, 'state_id' => 26, 'name' => 'دلفان'],
            ['id' => 290, 'state_id' => 26, 'name' => 'سلسله'],
            ['id' => 291, 'state_id' => 26, 'name' => 'کوهدشت'],
            ['id' => 292, 'state_id' => 26, 'name' => 'الشتر'],
            ['id' => 293, 'state_id' => 26, 'name' => 'نورآباد'],
            ['id' => 294, 'state_id' => 27, 'name' => 'آمل'],
            ['id' => 295, 'state_id' => 27, 'name' => 'بابل'],
            ['id' => 296, 'state_id' => 27, 'name' => 'بابلسر'],
            ['id' => 297, 'state_id' => 27, 'name' => 'بهشهر'],
            ['id' => 298, 'state_id' => 27, 'name' => 'تنکابن'],
            ['id' => 299, 'state_id' => 27, 'name' => 'جویبار'],
            ['id' => 300, 'state_id' => 27, 'name' => 'چالوس'],
            ['id' => 301, 'state_id' => 27, 'name' => 'رامسر'],
            ['id' => 302, 'state_id' => 27, 'name' => 'ساری'],
            ['id' => 303, 'state_id' => 27, 'name' => 'سوادکوه'],
            ['id' => 304, 'state_id' => 27, 'name' => 'قائم شهر'],
            ['id' => 305, 'state_id' => 27, 'name' => 'گلوگاه'],
            ['id' => 306, 'state_id' => 27, 'name' => 'محمود آباد'],
            ['id' => 307, 'state_id' => 27, 'name' => 'نکا'],
            ['id' => 308, 'state_id' => 27, 'name' => 'نور'],
            ['id' => 309, 'state_id' => 27, 'name' => 'نوشهر'],
            ['id' => 310, 'state_id' => 27, 'name' => 'فریدونکنار'],
            ['id' => 311, 'state_id' => 28, 'name' => 'آشتیان'],
            ['id' => 312, 'state_id' => 28, 'name' => 'اراک'],
            ['id' => 313, 'state_id' => 28, 'name' => 'تفرش'],
            ['id' => 314, 'state_id' => 28, 'name' => 'خمین'],
            ['id' => 315, 'state_id' => 28, 'name' => 'دلیجان'],
            ['id' => 316, 'state_id' => 28, 'name' => 'زرندیه'],
            ['id' => 317, 'state_id' => 28, 'name' => 'ساوه'],
            ['id' => 318, 'state_id' => 28, 'name' => 'شازند'],
            ['id' => 319, 'state_id' => 28, 'name' => 'کمیجان'],
            ['id' => 320, 'state_id' => 28, 'name' => 'محلات'],
            ['id' => 321, 'state_id' => 29, 'name' => 'بندرعباس'],
            ['id' => 322, 'state_id' => 29, 'name' => 'میناب'],
            ['id' => 323, 'state_id' => 29, 'name' => 'بندر لنگه'],
            ['id' => 324, 'state_id' => 29, 'name' => 'رودان-دهبارز'],
            ['id' => 325, 'state_id' => 29, 'name' => 'جاسک'],
            ['id' => 326, 'state_id' => 29, 'name' => 'قشم'],
            ['id' => 327, 'state_id' => 29, 'name' => 'حاجی آباد'],
            ['id' => 328, 'state_id' => 29, 'name' => 'ابوموسی'],
            ['id' => 329, 'state_id' => 29, 'name' => 'بستک'],
            ['id' => 330, 'state_id' => 29, 'name' => 'گاوبندی'],
            ['id' => 331, 'state_id' => 29, 'name' => 'خمیر'],
            ['id' => 332, 'state_id' => 30, 'name' => 'اسدآباد'],
            ['id' => 333, 'state_id' => 30, 'name' => 'بهار'],
            ['id' => 334, 'state_id' => 30, 'name' => 'تویسرکان'],
            ['id' => 335, 'state_id' => 30, 'name' => 'رزن'],
            ['id' => 336, 'state_id' => 30, 'name' => 'کبودر آهنگ'],
            ['id' => 337, 'state_id' => 30, 'name' => 'ملایر'],
            ['id' => 338, 'state_id' => 30, 'name' => 'نهاوند'],
            ['id' => 339, 'state_id' => 30, 'name' => 'همدان'],
            ['id' => 340, 'state_id' => 31, 'name' => 'ابرکوه'],
            ['id' => 341, 'state_id' => 31, 'name' => 'اردکان'],
            ['id' => 342, 'state_id' => 31, 'name' => 'بافق'],
            ['id' => 343, 'state_id' => 31, 'name' => 'تفت'],
            ['id' => 344, 'state_id' => 31, 'name' => 'خاتم'],
            ['id' => 345, 'state_id' => 31, 'name' => 'صدوق'],
            ['id' => 346, 'state_id' => 31, 'name' => 'طبس'],
            ['id' => 347, 'state_id' => 31, 'name' => 'مهریز'],
            ['id' => 348, 'state_id' => 31, 'name' => 'میبد'],
            ['id' => 349, 'state_id' => 31, 'name' => 'یزد'],
            ['id' => 350, 'state_id' => 32, 'name' => 'Fatih'],
        ];

        DB::table('cities')->insert($array);
    }
}
